# Generated by Django 3.1.4 on 2021-01-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20210116_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departamento',
            old_name='shor_name',
            new_name='short_name',
        ),
    ]
